stages:
  - stage: build
    displayName: build and push
    jobs:
      - job: docker_build
        steps:
        - task: DockerInstaller@0
          inputs:
            dockerVersion: '17.09.0-ce'
        - task: Docker@2
          inputs:
            containerRegistry: 'docker_acr'
            repository: 'DockerACR001'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            addPipelineData: false
            addBaseImageData: false
        
